### ISSUE TITLE
Basic example

### ISSUE THREAD

**Issue by timpuri** [PixelStereo/pyviscam#1]
Do you have any basic example file for using this library?

**Comment by reno-** [comment]
sorry, this library is in development. It will be ready by the end of 2015.
Have a look at  https://github.com/mutax/PyVisca

**Comment by timpuri** [comment]
Ok, thank you!

**Comment by ancipital** [comment]
Oh, bother, I was about to ask something similar.. It looks like you've done a lot of cleaning up, structuring and bringing sanity to it, but a basic helloworld-level example would probably help.

It looks like you've moved the serial port setup out of the library, which is fair enough- and that we should pass a handle to serial when creating a visca object..  It would be really nice to see a simple example of how _you_ structure the setup.. 

"WE NEED AN INIT FILE TO SEND ADDRESS_SET AND _if_clear" is a bit cryptic. I'm guessing we need to enumerate and so forth, but wonder about "an init file".

A really simple example that just opens a port, finds the camera and sends a couple of commands successfully would be worth its weight in gold, doesn't need to be pretty or take very long. I'd just like to see how you mean it to fit together.

**Comment by reno-** [comment]
Hi @ancipital , I didn't find the time to finish this project, and I don't know if I could do it this year.
Be sure that I will leave a message here when I will finish it, with a simple exemple of course !

**Comment by reno-** [comment]
Hi @ancipital, @timpuri  , I just push a simple exemple, if you're still interessed.

**Comment by ancipital** [comment]
Thanks :) I will take a look!

## 

"I'm the Bishop of Southwark, it's what I do"

---
